### PR TITLE
resubmission 1 and submission 2

### PR DESCRIPTION
**Pull request by simon-schaefer**

### CODE REVIEW

**Comment by simon-schaefer** [comment]
According to submission 2: Submitted folder does not contain the bag files, as all of them are larger than 100 MB and therefore exceed the limits of git pushs (also after "rosbag compress").

**Comment by selcukercan** [comment]
@SeleSchaefer please check this post https://duckietown.slack.com/archives/GDAS0GN8P/p1540557321007300

**Comment by simon-schaefer** [comment]
thanks ! resubmitted with bags using git lfs :)

**Comment by raabuchanan** [comment]
@selcukercan Are you going to merge this?

**Comment by selcukercan** [comment]
@manishpra why hasn't this been merged?

**Comment by simon-schaefer** [comment]
Should I do anything  here to enable the merge ? 🙈

**Comment by simon-schaefer** [comment]
closed for new pull request, as discussed with @manish-pra

**Pull request closed without merging**
